name: projet_dac
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.4.0
  video_player: ^2.5.1
  carousel_slider: ^4.2.1
  getwidget: ^3.0.1
  google_fonts: ^4.0.1
  fl_chart: ^0.60.0
  scaled_list: ^2.0.0
  footer: ^0.0.4
  fan_carousel_image_slider: any
  widget_slider: ^0.1.0
  sizer: ^2.0.15
  shared_preferences: ^2.0.17
  http: any
  filter_list: any
  go_router: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
